### ISSUE TITLE
Accuracy over 100%

### ISSUE THREAD

**Issue by Lenkense** [tsoding/zzzwe#44]
It is possible to get accuracy over 100%

![imagen](https://user-images.githubusercontent.com/77396360/114282946-6e49ee00-9a1d-11eb-889c-152d956a7a73.png)
![imagen](https://user-images.githubusercontent.com/77396360/114283612-fa114980-9a20-11eb-9207-515888e9b27d.png)
![imagen](https://user-images.githubusercontent.com/77396360/114283633-157c5480-9a21-11eb-9b72-2ca4b432960b.png)

A bullet can kill multiple enemies, this counts as  multiple hits with the same bullet and can create accuracy higher than 100%. Maybe this was made on purpose. Was this intended?

In the loop at index.js 830 while looping over enemies and bullets, bullets are not filtered in the loop. They are filtered at line 862 in index.js. This makes it so that, while looping over the enemies, enemy2 is hit by the same bullet that hit enemy1. Since bullets are not filtered, the hit is count twice.

changing line 836

`                        this.player.accuracy += 1;`
with

`                        this.player.accuracy += ( (bullet.lifetime > 0.0) ? 1 : 0 );`

should fix this.

**Comment by rexim** [comment]
@Lenkense the problem was addressed in #45 Please check out on the latest version and close this issue if the problem is fixed for you.

**Comment by Lenkense** [comment]
indeed it is fixed!
